antialiased: false
app_embed_dim: 16
app_opt: false
app_opt_lr: 0.001
app_opt_reg: 1.0e-06
batch_size: 1
bilateral_grid_shape: !!python/tuple
- 16
- 16
- 8
camera_model: pinhole
ckpt: null
compression: null
data_dir: /teamspace/lightning_storage/final_project_3DGS/data/tiger_colmap
data_factor: 1
depth_lambda: 0.01
depth_loss: false
disable_video: true
disable_viewer: true
eval_steps:
- 30000
far_plane: 10000000000.0
global_scale: 1.0
init_extent: 3.0
init_num_pts: 100000
init_opa: 0.5
init_scale: 0.1
init_type: sfm
lpips_net: alex
max_steps: 30000
means_lr: 0.00016
near_plane: 0.01
normalize_world_space: true
opacities_lr: 0.05
opacity_reg: 0.01
packed: false
patch_size: null
ply_steps:
- 7000
- 30000
port: 8080
pose_noise: 0.0
pose_opt: false
pose_opt_lr: 1.0e-05
pose_opt_reg: 1.0e-06
quats_lr: 0.001
random_bkgd: false
render_traj_path: interp
result_dir: /teamspace/lightning_storage/final_project_3DGS/trained_models/tiger_training
resume: null
save_ply: false
save_steps:
- 30000
scale_reg: 0.01
scales_lr: 0.005
sh0_lr: 0.0025
shN_lr: 0.000125
sh_degree: 3
sh_degree_interval: 1000
sparse_grad: false
ssim_lambda: 0.2
steps_scaler: 1.0
strategy: !!python/object:gsplat.strategy.mcmc.MCMCStrategy
  cap_max: 1000000
  min_opacity: 0.005
  noise_lr: 500000.0
  refine_every: 100
  refine_start_iter: 500
  refine_stop_iter: 25000
  verbose: true
tb_every: 100
tb_save_image: false
test_every: 8
use_bilateral_grid: false
use_fused_bilagrid: false
visible_adam: false
with_eval3d: false
with_ut: false
